Option to enable automatic pausing when in the menu
FrodeSolheim/fs-uae pull request #249
Opened 2021-02-14 11:48 UTC by mrsilver76

Second attempt to resolve FrodeSolheim/fs-uae#4 after I accidentally mangled my fork the first time around 🙄 

- Added an option `menu_auto_pause` which (when enabled) automatically pauses emulation when the menu is displayed.
- By default is off, maintaining existing user experience
- Updated documentation to detail the setting

2021-02-16 20:22 UTC, FrodeSolheim commented
This looks fine, except one thing that occurred to me while reviewing the code: Right now it will unpause when leaving the menu, no matter why/how it was paused in the first place. So, there needs to be a variable storing whether the emulator was paused due to menu_auto_pause or not, and only unpause on closing the menu if this variable is true.

2021-02-16 22:46 UTC, FrodeSolheim requested changes
This looks fine, except one thing that occurred to me while reviewing the code:

2021-02-16 22:46 UTC, FrodeSolheim commented on libfsemu/src/emu/menu.c
> +        fs_emu_pause(-1);
Right now it will unpause when leaving the menu, no matter why/how it was paused in the first place. So, there needs to be a variable storing whether the emulator was paused due to menu_auto_pause or not, and only unpause on closing the menu if this variable is true.

2021-02-16 22:46 UTC, FrodeSolheim commented on libfsemu/src/emu/menu.c
> +        fs_emu_pause(-1);
Also, presumably, it's fs_emu_pause(0); to disable the pause (didn't check though)

2021-02-20 21:56 UTC, mrsilver76 commented on libfsemu/src/emu/menu.c
> +        fs_emu_pause(-1);
Makes sense. Have now updated it to only un-pause if you've entered the menu and it's been automatically paused. If it's paused prior to entering the menu or you change the pause state whilst you're in the menu then the state will be maintained when you leave the menu. As for `0` vs `-1`, both seem to work, although I've changed it to `0` to be on the safe side.

2021-02-21 11:50 UTC, FrodeSolheim commented on libfsemu/src/emu/menu.c
> +    if (g_fs_emu_resume_on_menu_exit == 1 && fs_emu_is_paused() && fs_config_get_boolean("menu_auto_pause") == 1)
Checking for fs_config_get_boolean("menu_auto_pause") isn't really necessary here, the g_fs_emu_resume_on_menu_exit is sufficient, but it does not cause any issues, and this code will be obsolete with FS-UAE 4.x anyway, so it can stay

2021-02-21 11:52 UTC, FrodeSolheim approved these changes

2021-02-21 12:40 UTC, mrsilver76 commented on libfsemu/src/emu/menu.c
> +    if (g_fs_emu_resume_on_menu_exit == 1 && fs_emu_is_paused() && fs_config_get_boolean("menu_auto_pause") == 1)
I did debate just having that test but decided you might ding me for making an assumption that may not be true in the future :)

2021-02-23 17:00 UTC, FrodeSolheim commented
Looking good, only thing that needs to be done is to rebase against the fs-uae-3.0 branch and do a pull request against that instead of master. Is that something your comfortable doing? If not, then I can help with that.

2021-02-24 14:20 UTC, mrsilver76 commented
Blimey, not something I’ve done before but I’ll happily give it a go. Leave it with me and I’ll see what I can do. Thanks for the offer of help :)

Do you have any dates in mind for a final release of the 3.x branch? Looking forward to playing with 4.x.

2021-02-24 21:20 UTC, mrsilver76 commented
Long story short, the way my environment is set up means that following (albeit not very simple) instructions to rebase don't seem to work for me. 

If you would be so kind as to squash and rebase for me then I'd really appreciate it. In return 'll go back to reading "git for dummies"! 

Thanks :)

2021-03-14 12:13 UTC, blubberdiblub commented
@mrsilver76

As I don't know how your (or any for that matter) IDE presents and uses git (in case you use an IDE), I'm going to show you how to do this on the command line. Even with Git-for-Windows you can do this on the command line with the same commands (provided it was installed with one of the two options that will put git into your execution path).

Make sure your current working directory on the command line is inside the repository.

First, make sure you have both your and Frode's github repos set up as remote repositories in your local repo:

```bash
git remote -v

# should produce following output:
origin  git@github.com:mrsilver76/fs-uae.git (fetch)
origin  git@github.com:mrsilver76/fs-uae.git (push)
upstream        https://github.com/FrodeSolheim/fs-uae.git (fetch)
upstream        https://github.com/FrodeSolheim/fs-uae.git (push)
```

In case it is already set up like this, you can skip the next step. If your remote repo names are different from _origin_ and _upstream_, replace my usage of those names with yours in all following stuff.

However, I'm going to assume that your _origin_ is already set up like above, **but _upstream_ is missing**. In that case simply do this:

```bash
git remote add --fetch upstream https://github.com/FrodeSolheim/fs-uae.git
```

Now `git remote -v` output should look like above.

Adding Frode's upstream repository as remote makes it possible for you to refer to upstream branches and commits, rebase against them, cherry-pick from them et cetera, **independent** from the state of your personal branches.

Make sure your local view of the upstream repo is current (if you just added it or nothing changed upstream since last fetching, nothing will happen here, but it's good to make sure):

```bash
git fetch upstream
```

Make sure you are currently in your own master branch (i.e. the one connected to _origin_) and that it's clean - i.e. has no pending changed files, additions or anything:
```bash
git status

# should output:
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

If you're on a different branch, change to master with `git checkout master`.

Verify that you see the commits you made on top of upstream:

```bash
git log upstream/master..HEAD

# should output something like this:

commit 341989712e8714317307a0024965ac968b41d4c7 (HEAD -> master, origin/master)
Author: mrsilver76 <5719686+mrsilver76@users.noreply.github.com>
Date:   Sat Feb 20 21:49:50 2021 +0000

    Auto-unpause on menu exit only if auto-paused

commit a25b967221e18f0058794153e73209c6405ec327
Author: mrsilver76 <5719686+mrsilver76@users.noreply.github.com>
Date:   Sun Feb 14 11:46:52 2021 +0000

    Added ability to pause emulation whilst in the menu

commit 6e23130a0c623aa667263dd646081386a55864c0
Author: mrsilver76 <5719686+mrsilver76@users.noreply.github.com>
Date:   Sun Feb 14 11:46:00 2021 +0000

    Added details on how to pause emulation when in the menu

commit ab947a54ea4c4ac2db5ff24f60d4dc15cd9562ce
Author: mrsilver76 <5719686+mrsilver76@users.noreply.github.com>
Date:   Sun Feb 14 11:44:47 2021 +0000

    Added details on how to pause emulation when in the menu
```

Now create a branch that will later (when we're done) reflect the upstream _fs-uae-3.0_ branch with your changes on top and it will be ready to submit as pull request.
However, it will **start out** as a clone of your current changes **based on _master_**.
Also make sure you switch to the newly created branch:

```bash
git branch fs-uae-3.0
git checkout fs-uae-3.0
# As alternative to the two commands above, you could do it in one step (note the -b): git checkout -b fs-uae-3.0
```

In case it complained that there is already such a branch or you mess something up later and want to start over, you can do this (don't worry, it will not delete anything on your remote github repo, this is purely local):

```bash
git checkout master        # make sure you're safely back in your own master branch
git branch -D fs-uae-3.0   # that's a capital D, to force deletion

# then redo the branch cloning from above:
git branch fs-uae-3.0
git checkout fs-uae-3.0
```

Now lets go about rebasing, there'll be a little hitch, though.


### The Straightforward Way

As the upstream _master_ and _fs-uae-3.0_ branches are not directly based on each other, but are related by cherry-picks and merges instead (as is common), naively doing `git rebase upstream/fs-uae-3.0` would result in chaos.

Therefore what we'll do instead is basically cutting your changes from atop the _master_ branch and paste them back **onto** the _fs-uae-3.0_ branch. That corresponds to the `--onto` option of `git rebase`.

First, we have to ascertain the point to cut. We could do this with just counting your commits on top, but that's error-prone. There's a better way:

```bash
git merge-base HEAD upstream/master

# This will output a commit ID like so:
5e1f96c0c49ed1261619db057056bf73319ffa48
```

Highlight and copy that commit ID to your clipboard. (Alternatively you could also just type out the first few characters instead, abbreviating works.)

If you now show the commit log with `git log 5e1f96c0c49ed1261619db057056bf73319ffa48..HEAD` (note the `..HEAD` at the end) it should just show your 4 commits.

Now we can start the rebase:

```bash
git rebase --onto upstream/fs-uae-3.0 5e1f96c0c49ed1261619db057056bf73319ffa48
# use the commit ID you got earlier in case it is different
```

In an ideal world where none of your commits conflict with the base branch commits conflict, this would just have went through and you would've been as good as done.

Unfortunately, there is a conflicting change in the README (of all things). When a rebase fails, it's in an intermediate state where you have to either resolve the conflict or abort the rebase (which goes back to the state before the rebase). We will resolve the conflict - it's a good training, as this can happen any time.

Open up the files git told you are conflicting in an editor of your choice. _Notepad++_ will do or your IDE or any other editor that supports unix line endings. You can also use `vi`, if you're comfortable with it.

Search for the `<<<<<<` marker in the file. In what I see there's something like this:

```
[...]

<<<<<<< HEAD
You use the same key/button to dismiss the menu.
=======
By default, the emulator will continue to run whilst the menu is being displayed.
If you would like to change this so that it's automatically paused when you enter
the menu and resumes when you exit then you should add the option
`menu_auto_pause = 1`.

In the menu, you use the following keys for navigation:
>>>>>>> ab947a54 (Added details on how to pause emulation when in the menu)

In the menu, you use the following keys for navigation:
[...]
```

The stuff between `<<<<<<<` and `=======` is what the base branch changed or what their version of the section is, respectively. The stuff between `=======` and `>>>>>>>` is what your commits changed or what your version is.

In our case we probably want to keep both (including the "You use the same key/button to dismiss the menu." line) and arrange it meaningfully. So **delete all 3 conflict markers**, insert an empty line between the "You use [...]" and "By default, [...]" line and remove the duplicated "In the menu, [...]" line along with one empty line that is too many now.

Now mark your files you resolved conflicts for to go into the commit (similar to what you would do for a new commit):

```bash
git add README
```

If in the next step you don't want to be bothered with git firing up an editor to review your old commit message (as this may very well be _vi_, which you might be unfamiliar with), commit explicitly, replicating your old commit message:

```bash
git commit -m "Added details on how to pause emulation when in the menu"
```

Then, in either case, continue the rebase:

```bash
git rebase --continue

# something similar to this output should appear, possibly af [...]

2021-03-14 13:23 UTC, Rhialto commented
@blubberdiblub I like your extensive git instructions, but I think I can add some information that will make things easier in the future. @mrsilver76 

The github workflow with pull requests works a lot easier if you do your work on a separate branch, that has a new name. A name that isn't used yet by the upstream repo. If you do it like that, you can set up the upstream repo as described, and any changes in its `master` branch (etc) can't possibly conflict with changes you might have made (since you didn't make any changes on that branch).

Furthermore, make a new branch for each merge request. If you add more commits to a branch that's already used in a merge request, github will also add them to the merge request.

And it's easiest, if you want to contribute to some branch, say `fs-uae-3.0`, to first check out that branch, and then create your new contribution branch from there. Then your changes will automatically apply cleanly to that branch.

2021-03-24 17:05 UTC, mrsilver76 commented
@blubberdiblub That is the most amazing set of instructions. Thank you very much for what is, clearly, a tonne of time and effort you've taken into writing those.

I've managed to successfully rebase and issued a new PR. It's given it another number (#256) which I assume is what you'd normally expect and that this one will eventually get closed?

Once again, thank you!

2021-03-24 18:47 UTC, FrodeSolheim commented
The new pull request has been merged, thanks :)

2021-03-24 18:47 UTC, closed without merging